# Generated by Django 5.0.2 on 2024-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='days',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='eat_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='medicine_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='medicine_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='medicine_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='medicine_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sleep_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sleep_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(choices=[('sleep', 'Sleep'), ('medicine', 'Medicine'), ('eat', 'Eat')], max_length=255),
        ),
    ]
