# Generated by Django 5.0.2 on 2024-03-22 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activity_start_time_activity_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='days',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=datetime.date.today, max_length=50),
        ),
    ]
