# Generated by Django 5.0.2 on 2024-03-23 00:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=100),
        ),
    ]
