# Generated by Django 5.0.2 on 2024-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='eat_start_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='medicine_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sleep_start_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='days',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=255),
        ),
    ]
