# Generated by Django 5.0.2 on 2024-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_rename_eat_start_time_activity_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='medicine_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
