# Generated by Django 5.0.2 on 2024-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_medicine_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
