# Generated by Django 5.0.5 on 2024-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('sleep', 'Sleep'), ('medicine', 'Medicine'), ('eat', 'Eat')], max_length=20)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
