# Generated by Django 5.0.2 on 2024-03-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, upload_to='chat_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autismChat.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autismChat.group'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
